Travis
emotz/kladovka pull request #106
Opened 2017-09-08 09:21 UTC by ITarako

2017-09-08 09:29 UTC, Eoksni requested changes

2017-09-08 09:29 UTC, Eoksni commented on .travis.yml
> +- docker-compose exec dev npm test
few things:
we don't need webpack --watch, we just need to build it once
we don't need webpack or selenium at all for domain tests or REST API tests

Please try to follow this rule - execute test-actions one by one in order of "how much do I need to run it"
domain tests only need mongo-server and express to be running, and so are REST API tests
e2e tests require everything - selenium, mongo, express, webpack
So first start up mongo and express and run domain tests and, if possible, REST API tests
then build webpack (without --watch), then start up selenium, then run e2e tests

and comment out restriction "only master branch" for now, to test how it actually works on travis

2017-09-08 09:31 UTC, Eoksni commented on .travis.yml
> +- docker-compose exec dev npm test
oh, and you forgot about `cp config.json.example config.json`

2017-09-08 09:38 UTC, Eoksni commented on .travis.yml
> +- docker-compose exec dev npm test
actually, I think I was wrong - domain tests don't require express, only mongo, right?

2017-09-08 09:41 UTC, Eoksni commented on .travis.yml
> +- docker-compose exec dev npm test
and if we specify memory db in config, they don't require even mongo, right?
so even better approach would be 
- run lint
- copy config, set memory db for tests in config
- run domain tests
- set mongo db for tests in config
- start mongo server
- run only db tests among domain tests
- webpack
- start selenium
- run e2e tests

2017-09-08 09:44 UTC, Eoksni commented on .travis.yml
> +- docker-compose exec dev npm test
and don't do `npm run deps`, install node modules as they are required
before running domain tests, install node modules for domain,
before running express, install node modules for backend, etc

2017-09-08 10:17 UTC, Eoksni commented on .travis.yml
> +- docker-compose exec dev npm test
we may even run memory domain tests before doing any docker-shenanigans

2017-09-08 12:16 UTC, ITarako commented
after your command config.json is empty

2017-09-08 12:30 UTC, Eoksni commented
fml, ok, but at least 
`cp tmp.json config.json && rm tmp.json`
->
`mv tmp.json config.json`

2017-09-09 05:53 UTC, Eoksni approved these changes

2017-09-09 06:32 UTC, merged